ca_cert: &ca_cert 'C:/ProgramData/QuLab/ca.pem'
db:
  db: lab
  host: ['localhost']
  #host: '[10.122.7.18, 10.122.7.19, 10.122.7.20]'
  #username: qulab_admin
  #password: qulab_password
  #authentication_source: qulab
  #replicaSet: rs0
  #ssl: 'true'
  #ssl_ca_certs: '*ca_cert'
  #ssl_match_hostname: 'true'
server_port: '8123'
server_name: '[localhost, 127.0.0.1, 10.122.7.18]'
ssl:
  ca: '*ca_cert'
  cert: 'C:\ProgramData\QuLab\cert\server.crt'
  key: 'C:\ProgramData\QuLab\private\server.key'
